// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgBrxX8XJkiFAgV-4sDcxX-PvIrWxR_gk',
    appId: '1:305536261438:web:50f72f517262b7ea03a06f',
    messagingSenderId: '305536261438',
    projectId: 'movie-hub-flutter',
    authDomain: 'movie-hub-flutter.firebaseapp.com',
    storageBucket: 'movie-hub-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoXvGjASdgUK6ywxAN5NovHLXFO-bLiiM',
    appId: '1:305536261438:android:37e0ba7b4095e4fa03a06f',
    messagingSenderId: '305536261438',
    projectId: 'movie-hub-flutter',
    storageBucket: 'movie-hub-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuWUol9f8ajRxnjxOYVIrZFA2v-U0vvvs',
    appId: '1:305536261438:ios:95b249827fcc76cf03a06f',
    messagingSenderId: '305536261438',
    projectId: 'movie-hub-flutter',
    storageBucket: 'movie-hub-flutter.appspot.com',
    iosBundleId: 'com.example.movieHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuWUol9f8ajRxnjxOYVIrZFA2v-U0vvvs',
    appId: '1:305536261438:ios:95b249827fcc76cf03a06f',
    messagingSenderId: '305536261438',
    projectId: 'movie-hub-flutter',
    storageBucket: 'movie-hub-flutter.appspot.com',
    iosBundleId: 'com.example.movieHub',
  );
}
